### ISSUE TITLE
type 'Future<void>' is not a subtype of type 'WebViewController' in type cast

### ISSUE THREAD

**Issue by avelino** [Tensegritics/ClojureDart#237]
**Describe the bug**

it's probably my ignorance because I don't know Dart/Flutter well enough, but I can't use the `WebViewWidget`.

Is the way I am structuring the widget and the webview call correct?

package: https://pub.dev/packages/webview_flutter

**stdout:**
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building mainReify4wk9ma$1(dirty):
type 'Future<void>' is not a subtype of type 'WebViewController' in type cast

The relevant error-causing widget was:
  mainReify4wk9ma$1
  mainReify4wk9ma$1:file:///Users/avelino/projects/avelino/phanpy-app/lib/cljd-out/phanpy/main.dart:11:36

When the exception was thrown, this was the stack:
#0      mainReify4wk9ma$1.build (package:phanpy/cljd-out/phanpy/main.dart:22:231)
#1      StatelessElement.build (package:flutter/src/widgets/framework.dart:5156:49)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#4      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#9      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:939:7)
#13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════

Reloaded 2 of 736 libraries in 183ms (compile: 46 ms, reload: 72 ms, reassemble: 30 ms).
```

**source:**
```clj
(ns phanpy.main
  (:require ["package:flutter/material.dart" :as m]
            ["package:webview_flutter/webview_flutter.dart" :as wv]
            [cljd.flutter :as f]))


(def url (Uri/parse "https://phanpy.social/"))

(def wv-controller
  (.loadRequest (wv/WebViewController) url))

(defn main []
  (f/run
   (m/MaterialApp
    .theme (m/ThemeData .primarySwatch m.Colors/pink))
   .home (m/Scaffold)
   .body
   m/Center
   (wv/WebViewWidget .controller wv-controller)))
```

**Comment by dupuchba** [comment]
hello @avelino , try this instead

```
;; in jour `(ns... (:require ...)) add
["package:webview_flutter/webview_flutter.dart" :as webview]
["package:webview_flutter_platform_interface/webview_flutter_platform_interface.dart" :as webview-interface]
["package:webview_flutter_wkwebview/webview_flutter_wkwebview.dart" :as webview-ios]

; then define this function
(defn web-view [current-url]
  (f/widget
    :let [ios (dart/is? webview-interface/WebViewPlatform.instance webview-ios/WebKitWebViewPlatform)
          ;; you can customize parameters passed to the underlying platform ios/android
          params (if ios
                   (webview-ios/WebKitWebViewControllerCreationParams
                     .limitsNavigationsToAppBoundDomains true)
                   (webview/PlatformWebViewControllerCreationParams))]    
    :managed [controller
              (doto (webview/WebViewController.fromPlatformCreationParams params)
                ;; depending on your needs
                (.setJavaScriptMode webview/JavaScriptMode.unrestricted)
                (.setBackgroundColor m/Colors.white)
                (.enableZoom true)
                (.setUserAgent "ClojureDart")
                (as-> cont
                    (doto cont
                      (.setNavigationDelegate
                        (webview/NavigationDelegate
                          .onPageStarted (fn [_]
                                           ;; do smth here if you need to
                                           )
                          .onPageFinished (fn [_]
                                            ;; do smth here if you need to                                            
                                            )
                          .onNavigationRequest
                          (fn [{for-main-frame .-isMainFrame
                                url .-url :as ^webview/NavigationRequest nav}]
                            ;; this is just a suggestion, it depends on you problem
                            (if (or (not for-main-frame) (string/includes? url "myurl"))
                              webview/NavigationDecision.navigate
                              webview/NavigationDecision.prevent))
                          .onWebResourceError
                          (fn [{error-type .-errorType :as ^webview-interface/WebResourceError error}]
                            ;; handle error here
                            nil)))))
                (cond-> ios
                  (-> ^webview-ios/WebKitWebViewController (.-platform)
                    ;; if you want the user to be able to go back
                    (.setAllowsBackForwardNavigationGestures true)))                
                (.loadRequest (Uri/parse current-url)))
              :dispose false]
    
    (webview/WebViewWidget .controller controller)))

and call it in your main in place of `(wv/WebViewWidget .controller wv-controller)`
```
