### ISSUE TITLE
hot reload can't find  atom var

### ISSUE THREAD

**Issue by vinurs** [Tensegritics/ClojureDart#261]
this is the reproduce code
```
(ns app.main
  (:require
   ["dart:core" :refer [print]]
   ["package:flutter/material.dart" :as m]
   [cljd.flutter :as f]))

(def  counter (atom 0))

(def first-screen
  (f/widget
    :get [m/Navigator]
    (m/Scaffold
       .appBar (m/AppBar
                .title (m/Text "First Screen"))
       .body   (m/Center
                .child (m/ElevatedButton
                            .onPressed #(do
                                          (.pushNamed navigator "/second")
                                          nil)
                            .child     (m/Text "go second screen"))))))

(def second-screen
  (f/widget
    ;; :get []
    (m/Scaffold
       .appBar (m/AppBar
                .title (m/Text "Second Screen"))
       .body   (m/Center
                .child (m/ElevatedButton
                            .onPressed (fn []
                                         (reset! counter (+ 1 @counter))
                                         (print @counter))
                            .child     (m/Text "add counter"))))))


(defn main []
  (m/runApp
   (m/MaterialApp
    .title "Navigation Basics"
    .initialRoute "/"
    .routes       (into {}
                        (keep (fn [[k v]]
                                {k (fn ^m/Widget k [ctx]
                                     v )}))
                        {"/"       first-screen
                         "/second" second-screen}))))

```
then, go to second screen, click the `add counter` button, in the console ,it outputs ok,
and then , Just `add an empty line in the main.cljd ` to trigger hot reload. At this point, when you click the "add counter" button, you will notice an error being output below the console.
```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
No top-level getter 'counter$v1' declared.
Receiver: top-level
Tried calling: counter$v1
```
but if i uncomment the `;; get []`
```
(f/widget
     :get []
```
it will be ok
this is the log
```
Deleting .dart_tool...                                               2ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting Flutter.podspec...                                          0ms
Deleting ephemeral...                                                0ms
Deleting ephemeral...                                                0ms
Deleting ephemeral...                                                0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Resolving dependencies...
  built_value 8.6.1 (8.6.2 available)
  collection 1.17.1 (1.18.0 available)
  flutter_native_splash 2.3.1 (2.3.2 available)
  matcher 0.12.15 (0.12.16 available)
  material_color_utilities 0.2.0 (0.8.0 available)
  petitparser 5.4.0 (6.0.1 available)
  source_span 1.9.1 (1.10.0 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test_api 0.5.1 (0.6.1 available)
  win32 5.0.6 (5.0.7 available)
  xml 6.3.0 (6.4.2 available)
Got dependencies!
Resolving dependencies...
+ _fe_analyzer_shared 61.0.0 (64.0.0 available)
+ analyzer 5.13.0 (6.2.0 available)
+ async 2.11.0
+ collection 1.18.0
+ convert 3.1.1
+ crypto 3.0.3
+ file 7.0.0
+ glob 2.1.2
+ meta 1.9.1
+ package_config 2.1.0
+ path 1.8.3
+ pub_semver 2.1.4
+ source_span 1.10.0
+ string_scanner 1.2.0
+ term_glyph 1.2.1
+ typed_data 1.3.2
+ watcher 1.1.0
+ yaml 3.1.2
Changed 18 dependencies!

Compiling cljd.core to Dart 3
 - compiling cljd.core @11:48:21
 - writing compiled cljd.core to lib/cljd-out/cljd/core.dart @11:48:26

Compiling to Dart... @11:48:26
  app.main
 - compiling app.main @11:48:26
 - compiling cljd.flutter @11:48:30
 - compiling cljd.string @11:48:30
 - writing compiled cljd.core to lib/cljd-out/cljd/core.dart @11:48:31
 - writing compiled cljd.string to lib/cljd-out/cljd/string.dart @11:48:31
 - writing compiled cljd.flutter to lib/cljd-out/cljd/flutter.dart @11:48:31
 - writing compiled app.main to lib/cljd-out/app/main.dart @11:48:31
  Bravissimo! 👏 @11:48:31

Launching flutter run -d iPhone 14 Pro Max
Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
Running pod install...                                             612ms
Running Xcode build...
Xcode build done.                                           26.9s
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
Syncing files to device iPhone 14 Pro Max...                        77ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPhone 14 Pro Max is available at: http://127.0.0.1:64664/SuCq4_NLYOo=/
The Flutter DevTools debugger and profiler on iPhone 14 Pro Max is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:64664/SuCq4_NLYOo=/
flutter: 1
flutter: 2
flutter: 3
flutter: 4

Compiling to Dart... @11:49:18
  app.main
 - compiling app.main @11:49:18
 - writing compiled app.main to lib/cljd-out/app/main.dart @11:49:18
  I like when a plan comes together! 👨‍🦳 @11:49:18

Performing hot reload...
Reloaded 3 of 1003 libraries in 188ms (compile: 43 ms, reload: 49 ms, reassemble: 55 ms).

══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
No top-level getter 'counter$v1' declared.
Receiver: top-level
Tried calling: counter$v1

When the exception was thrown, this was the stack:
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:191:5)
#1      second_screen$v1.<anonymous closure> (package:app/cljd-out/app/main.dart:67:34)
#2      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154:21)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
#5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
#6      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:244:7)
#7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630:9)
#8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#9      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#11     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:465:19)
#14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:445:22)
#15     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:331:11)
#16     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:400:7)
#17     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:363:5)
#18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:320:7)
#19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:293:9)
#20     _invoke1 (dart:ui/hooks.dart:158:13)
#21     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#7fd06
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by vinurs** [comment]
can use `defonce` instead
