### ISSUE TITLE
Type cast error on latest blessed sha

### ISSUE THREAD

**Issue by valerauko** [Tensegritics/ClojureDart#319]
**Describe the bug**
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building watch_widget_caaxye$1(dirty, state:
WatchState#3db53(subscribable: Instance of 'Cell', current value: null)):
type 'AlwaysStoppedAnimation<dynamic>' is not a subtype of type 'Animation<Color?>?' in type cast

The relevant error-causing widget was:
  watch_widget_caaxye$1
  watch_widget_caaxye$1:file:///home/valerauko/[redacted]/lib/cljd-out/[redacted].dart:214:24

When the exception was thrown, this was the stack:
#0      ifn_widget_18695hm$1.$_invoke$1 (package:[redacted]/cljd-out/[redacted]:29:133)
#1      ifn_widget_18695hm$1.$_invoke$0 (package:[redacted]/cljd-out/[redacted]:23:31)
#2      watch_widget_caaxye$1.$_build$2 (package:[redacted]/cljd-out/[redacted]:89:42)
#3      WatchState.build (package:[redacted]/cljd-out/cljd/flutter.dart:1792:67)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:5599:27)
```

The offending widget is as follows
```clj
   (f/widget
    m/Center
    m/CircularProgressIndicator
    .valueColor
    (m/AlwaysStoppedAnimation color))
```

Does your problem persist after `clj -M:cljd clean && flutter clean`?
Yes

**To Reproduce**
After `cljd upgrade` the UI is full of the above exception

**Expected behavior**
No type cast error

**Comment by cgrand** [comment]
the warnings are red herrings and are fixed on main

**Comment by cgrand** [comment]
How is `color` defined?
If it's a compiler regression it looks like we lost the type of color and thus `(m/AlwaysStoppedAnimation color)` is not inferred to the right type.
The most recent change affecting inference is https://github.com/Tensegritics/ClojureDart/commit/4e80ee1ca52fec788f9b5a555e8f44299a67de8c

**Comment by cgrand** [comment]
@valerauko provided form is not enough to repro. Can you share more? At least how `color` is introduced.

**Comment by valerauko** [comment]
@cgrand here's a full main.cljd. This works on previous sha but results in error on latest.
```clj
(ns repro.main
  (:require ["package:flutter/material.dart" :as m]
            [cljd.flutter :as f]))

(defn loading
  ([]
   (loading (m/Color. 0xff3c434d)))
  ([^m/Color color]
   (f/widget
    m/Center
    m/CircularProgressIndicator
    .valueColor
    (m/AlwaysStoppedAnimation. color))))

(defn main []
  (f/run
   m/MaterialApp
   .home
   (f/widget
    m/Center
    (loading))))
```

**Comment by cgrand** [comment]
@valerauko e05433c2999af00b19c1ea5c6093f639d1d7d4c5 is the culprit! I wasn't suspecting that. Will fix asap.
Have you been able to work around the issue?

**Comment by valerauko** [comment]
For now, not upgrading to latest sha is the "workaround". It works fine on the previous blessed sha and I didn't see any critical changes that would require latest sha, so I can wait for the fix to be released~

**Comment by cgrand** [comment]
The afore-mentioned commit is sound. The expansion of f/widget changed and introduced an extra let.
Thus `(m/AlwaysStoppedAnimation. color)` was extracted instead of being inline.
When inline, it happened it stayed inline even in Dart. Thus leaving type inference to Dart.
When extracted, ClojureDart does the type inference and is oblivious to type variables.

```clojure
(deftest infer-type-args
  (let [e (MapEntry (str "a") (count "a"))]
    (is (instance? #/(MapEntry String int) e))))
```

fails currently, saying e is an instance of `MapEntry<dynamic, dynamic>`.

**Comment by cgrand** [comment]
the problem is not with `color` but with the  compiler failing (well not even trying) to infer the parametrized type of `(m/AlwaysStoppedAnimation. color)`. As long as there was no `let` it was ok because the non-parametrized type never appeared and then the Dart compiler inferred the right one.

**Comment by cgrand** [comment]
Obvious workaround in hindsight.
