### ISSUE TITLE
Destructuring on varargs do not work when invoked with 0 args

### ISSUE THREAD

**Issue by souenzzo** [Tensegritics/ClojureDart#96]
code
```clojure
(defn foo
  [& {:keys [bar]}]
  bar)

(defn main
  []
  (prn (foo)))

``` 

error

```dart
Unhandled exception:
type 'Null' is not a subtype of type 'List<dynamic>' in type cast
#0      $_map_lit (file:///home/souenzzo/src/aim/lib/cljd-out/cljd/core.dart:3274:16)
#1      foo$ifn.$_invoke$vararg (file:///home/souenzzo/src/aim/lib/cljd-out/aim/main.dart:35:23)
#2      IFnMixin_Z.$_invoke$0 (file:///home/souenzzo/src/aim/lib/cljd-out/cljd/core.dart:6813:14)
#3      main (file:///home/souenzzo/src/aim/lib/cljd-out/aim/main.dart:50:49)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

**Comment by souenzzo** [comment]
possible test
```clojure

(defn sample-destructure-test [& {:keys [foo]}] foo)

(deftest destructure-test
  (testing "Destructuring in many ways"
    (is (nil? (sample-destructure-test)))
    (is (zero? (sample-destructure-test :foo 0)))
    (is (zero? (sample-destructure-test :foo 1 :foo 0)))
    (is (nil? (sample-destructure-test :bar 1)))))

```
